### ISSUE TITLE
Why is link prediction setting in this literature referred to as 'unsupervised'?

### ISSUE THREAD

**Issue by DaehanKim** [vuptran/graph-representation-learning#4]
Hi,

I found that your literature actually uses true link information by using masked cross entropy loss. In what sense, is this setting called 'unsupervised' link prediction?

Thanks in advance.

**Comment by vuptran** [comment]
You are correct. This setting is not technically called unsupervised link prediction because it does require ground truth link labels. The description in the paper has an oversight.

**Comment by vuptran** [comment]
You raise a good point. In the common link prediction problem, we are given a partially observed graph with known links and non-links as the starting point. These are values of the data set, similar to pixel values of images. We use the values of the network to make predictions on unobserved entries in the network or adjacency matrix without requiring additional ground truth labels. In this sense, we are doing unsupervised link prediction by using only the input values of the adjacency matrix.

But your point is valid because we still need the ground truth link labels to make progress. A true unsupervised link prediction problem is where the adjacency matrix is completely unknown and the task is to predict the adjacency matrix from scratch. So what we are doing here is not entirely unsupervised link prediction, and you are correct.
